apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: odoo
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:17
        env:
        - name: HOST
          value: postgres
        - name: USER
          value: odoo
        - name: PASSWORD
          value: odoo
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-storage
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-storage
        persistentVolumeClaim:
          claimName: odoo-data
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  type: NodePort
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30007
  selector:
    app: odoo
